<link rel="stylesheet" href="css/modules/header.css" />
<link rel="stylesheet" href="css/modules/footer.css" />
<link rel="stylesheet" href="css/modules/menu.css" />
<link rel="stylesheet" href="css/main.css" />
<link rel="stylesheet" href="css/spa-supplement.css" />
<link rel="stylesheet" href="css/pages/home.css" />
<link rel="stylesheet" href="css/pages/info.css" />
<link rel="stylesheet" href="css/pages/evenementen.css" />
<link rel="stylesheet" href="css/pages/over-ons.css" />
<link rel="stylesheet" href="css/pages/contact.css" />
<link rel="stylesheet" href="css/pages/FAQ.css" />
<link rel="stylesheet" href="css/pages/nieuws.css" />